---
title: "1.1 — Introduction to Econometrics — Class Content"
draft: false
linktitle: "1.1 — Introduction"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
toc: true
slides: "01-slides"
---

{{% alert note %}}
*Monday, February 1, 2021*
{{% /alert %}}

{{% alert warning %}}
Please complete the [preliminary survey](/assignment/00-preliminary-survey) on statistics and software as soon as you can.
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

<span class="newthought">Welcome</span> to ECON 480 — Econometrics! Today's lesson will be an overview of the content and the assignments of the course. Please read and familiarize yourself with the [syllabus](/syllabus). 

This is not just a “syllabus day,” as we need to hit the ground running, beginning with learning the software we will be using this semester. Starting next class, we will do a deep dive in to R for about 2 weeks. In preparation, please do the following **before next class**:

1. Go to [RStudio.cloud](https://rstudio.cloud) and register a (free) account with your Hood details.

2. Try to [install R and R Studio](https://metricsf20.classes.ryansafner.com/reference/#installing-r-and-r-studio) on your computer if you are able, before next class. You will still always have RStudio.cloud available all to use in your browser, but it is much better to have a real version of `R` and `R Studio` on your own machine to work with all semester.

## <i class="fas fa-book-reader fa-lg"></i> Readings

Today is introductory, but please heed this timeless message:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A message to students from the Doggfather himself, <a href="https://twitter.com/SnoopDogg?ref_src=twsrc%5Etfw">@SnoopDogg</a> <a href="https://t.co/wsSANYv8u6">pic.twitter.com/wsSANYv8u6</a></p>&mdash; Ryan Briggs (@ryancbriggs) <a href="https://twitter.com/ryancbriggs/status/1293543531496308736?ref_src=twsrc%5Etfw">August 12, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Please note going forward, the lesson numbers and topics (e.g. 1.1) are *my* design, and will not match up with the textbook!

### Optional/Referenced Readings

- July 2 2003, [<i class="fas fa-external-link-square-alt"></i> “Why Dolphins are Deep Thinkers”](https://www.theguardian.com/science/2003/jul/03/research.science), *The Guardian*]
- January 17, 2021, [<i class="fas fa-external-link-square-alt"></i> These Monkeys Understand Economics and Intentionally Steal High-Ticket Items to Barter for Better Food, Study Finds](https://gizmodo.com/these-monkeys-understand-economics-and-intentionally-st-1846078932?utm_medium=sharefromsite&utm_source=_facebook), *Gizmodo*

## <i class="fas fa-chalkboard-teacher"></i> Slides

`r blogdown::shortcode("slide-links")`

{{% div fyi %}}
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
{{% /div %}}

## <i class="fas fa-dumbbell"></i> Practice

NONE

## <i class="fas fa-laptop-code"></i> Assignments

### Preliminary Math Survey Due Sunday Feb 7

Please take the [preliminary survey](/assignment/00-preliminary-survey) on your statistics and software background by 11:59 PM Sunday. This will help us all have a productive semester together.