---
title: "1.3 — Data Visualization with ggplot2 — Class Content"
draft: false
linktitle: "1.3 — Data Visualization with ggplot2"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.3-slides"
---

{{% alert note %}}
*Tuesday, August 30, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we start the fun stuff - data visualization. We will cover how to build plots with the package `ggplot2` (part of the `tidyverse`): I will lecture for the first half (again, it will be a lot of information that you can refer back to as needed over the semester) and you will practice making plots.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-external-link-square-alt"></i>Ch.3 in Wickham & Grolemund, [http://r4ds.had.co.nz/introduction.html](R for Data Science)

### On `ggplot2`

- **R Studio's [ggplot2 Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)**
- **`ggplot2`'s website [reference section](https://ggplot2.tidyverse.org/reference/index.html)**
- Hadley Wickham's[ R for Data Science book chapter on ggplot2](http://r4ds.had.co.nz/data-visualisation.html)
- STHDA's [be awesome in ggplot2](http://www.sthda.com/english/wiki/be-awesome-in-ggplot2-a-practical-guide-to-be-highly-effective-r-software-and-data-visualization)
- r-statistic's [top 50 ggplot2 visualizations](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)

### On data visualization

- **Kieran Healy's [Data Visualization: A Practical Guide](http://socviz.co/)**
- **Claus Wilke's [Fundamentals of Data Visualization](https://serialmentor.com/dataviz)**
- PolicyViz [Better Presentations](https://policyviz.com/) 
- Karl Broman's [How to Display Data Badly](https://www.biostat.wisc.edu/~kbroman/presentations/IowaState2013/graphs_combined.pdf)
- [I Want Hue](http://tools.medialab.sciences-po.fr/iwanthue/) 

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-registered"></i> R Practice

Answers from last class’ practice problems on base R are posted [on that page](/r/1.2-r). Today you will be working on [R practice problems](/r/1.3-r) on data visualization. Answers will be posted later on that page.

## <i class="fas fa-laptop-code"></i> Assignments

### Preliminary Statistics Survey

[“Answers”](/assignment/00-preliminary-survey-answers.html) for the statistics survey have been posted, including some summaries of how your classmates feel.

## Additional Useful Information

### New Packages Mentioned

Learn more about each of these in context in the slides, but below are links to each packages’s online help pages, which include descriptions of how each function works, examples, and cheatsheets to help you

- [`ggplot2`](https://ggplot2.tidyverse.org/) a grammar of graphics for ploting

Check back here later for more tips on plotting with ggplot2!