---
title: "1.5 — Optimize Your Workflow with Projects, Markdown, and Git — Class Content"
draft: false
linktitle: "1.5 — Optimize Your Workflow"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.5-slides"
---

{{% alert note %}}
*Tuesday, September 7, 2021*
{{% /alert %}}

{{% alert warning %}}
[Problem Set 1](/assignments/01-problem-set) is due by **DATE**. 
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today I will give you about half the class period to finish your [1.4 practice problems](/r/1.5-r) and I can answer questions. Then I will briefly show you how you the magic of how you can improve your workflow, efficiency, automation, reproducibility, and safe file backups with R Markdown, R Projects, git and github. All of these tools are slightly advanced, and *optional* for you to use, but the learning curve pays off very high returns for the rest of your life! A good handful of people every semester tell me that they keep using these tools years in the future.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-external-link-square-alt"></i> Chs. 8, 27, 28, 29, 30 (but especially 27) in Wickham & Grolemund, [R for Data Science](http://r4ds.had.co.nz/)

### On Plain-Text Workflow

- Healey, Kieran, [*The Plain Person’s Guide to Plain Text Social Science*](http://plain-text.co/)

### On Markdown Syntax

- [Markdown tutorial](https://www.markdowntutorial.com/)

### On R Markdown
- Xie, Yihui, J.J. Allaire, and Garett Grolemund, [*R Markdown: The Definitive Guide*](https://bookdown.org/yihui/rmarkdown/)
- RStudio, [*R Markdown Reference Guide*](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
- RStudio, [*Overview of R Markdown*](https://rmarkdown.rstudio.com/)
- Rstudio, [*R Markdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

### On Git and Github

- Bryan, Jenny and Jim Hester, [*Happy Git and GitHub for the useR*](https://happygitwithr.com/)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-registered"></i> R Practice

Answers from last class’ practice problems on base R are posted [on that page](/r/1.4-r). Today’s "[practice problems](/r/1.5-r)" get you to practice the tools we are working with today. They are again not required, but will help you if you are interested.

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 1

[Problem Set 1](/assignments/01-problem-set) is posted and is due by **DATE**. Please see the instructions for more information on how to submit your assignment (there are multiple ways!).
