---
title: "2.7 — Inference for Regression — Class Content"
draft: false
linktitle: "2.7 — Inference for Regression"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 13
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.7-slides"
---

{{% alert note %}}
*Thursday, September 30, 2021* and *Tuesday, October 5, 2021*
{{% /alert %}}

{{% alert warning %}}
[Problem Set 3](/assignments/03-problem-set) is due by the end of the day Thursday, October 7.
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we finish our discussion of statistical inference, focusing on hypothesis testing about our regression. We will hopefully have time at the end to work on a few practice problems.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch.4 in Bailey, *Real Econometrics*
- [<i class="fas fa-external-link-square-alt"></i> Ch. 10 (optionally 8-9) in *Modern Dive* ](https://moderndive.netlify.com/10-inference-for-regression.html)
- [<i class="fas fa-external-link-square-alt"></i> Visualizing Probability and Inference ](https://seeing-theory.brown.edu/frequentist-inference/index.html)
- [<i class="fab fa-youtube"></i> *Last Week Tonight with John Oliver*: Scientific Studies](https://www.youtube.com/watch?v=0Rnq1NpHdmw)
- [“There is Still Only One Test”](https://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html)

The readings are the same as last class, plus one highly recommended additional video: be sure to watch the excellent and hilarious discussion of the limits and misuses of scientific studies and statistical significance $(p$-values) in the *Last Week Tonight* clip. I also added the blog post that I reference in class about all hypothesis testing is really one common procedure.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-registered"></i> R Practice

Today you will be working on [R practice problems](/r/2.7-r) on regression. Answers will be posted later on that page.

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 3 Due Thurs Oct 7
[Problem Set 3](/assignments/03-problem-set) is due by the end of the day on Thursday, October 7.

## New Packages Mentioned

- `infer`: for simulation for statistical inference