---
title: "3.4 — Multivariate OLS Estimators: Bias, Precision, and Fit — Class Content"
draft: false
linktitle: "3.4 — Multivariate OLS Estimators: Bias, Precision, & Fit"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 16
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.4-slides"
---

{{% alert note %}}
*Thursday, October 28, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we continue looking at multivariate regression, and see how the introduction of additional variables affects our model: the interpretation of the marginal effects (and we will measure an example of omitted variable bias), the standard errors of the estimators, and the goodness of fit of the regression.

We continue the extended example about class sizes and test scores, which comes from a (Stata) dataset from an old textbook that I used to use, [Stock and Watson, 2007](https://www.pearson.com/us/higher-education/product/Stock-Introduction-to-Econometrics-Update-3rd-Edition/9780133486872.html?tab=resources). Download and follow along with the data from today's example:^[Note this is a `.dta` Stata file. You will need to (install and) load the package `haven` to `read_dta()` Stata files into a dataframe.]

- [<i class="fas fa-table"></i> `caschool.dta`](http://metricsf21.classes.ryansafner.com/data/caschool.dta)

I have also made a RStudio Cloud project documenting all of the things we have been doing with this data that may help you when you start working with regressions:

- [<i class="fas fa-cloud"></i> Class Size Regression Analysis (Cloud R project)](https://rstudio.cloud/spaces/163934/project/2940189)
- [<i class="fas fa-external-link-square-alt"></i> Class Size Regression Analysis (output)](/data/class_size_regression_analysis.html)

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 5.1, 5.2, 5.4 in Bailey, *Real Econometrics*

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-registered"></i> R Practice

Today you will be working on [R practice problems](/r/3.4-r) on multivariate regression. Answers will be posted later on that page.

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 4 Due Thurs Nov 4
[Problem Set 4](/assignments/04-problem-set) is due by the end of the day on Thursday, November 4.
