---
title: "3.5 — Reading and Writing Empirical Papers — Class Content"
draft: false
linktitle: "3.5 — Reading and Writing Empirical Papers"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 17
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.5-slides"
---

{{% alert note %}}
*Tuesday, November 2, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we discuss the elements of a good empirical paper, with an eye towards your [paper projects](/assignments/research-aperp).

I highly recommend you look at my example repositories:

- [<i class="fab fa-github"></i> Workflow](https://github.com/ryansafner/workflow)
- [<i class="fab fa-github"></i> Example Empirical Paper](https://github.com/ryansafner/example_empirical_paper)

The first is one that I showed you back in [class 1.5](/content/1.5-content) when we talked about R Markdown and having a reproducible, plain-text, workflow. It has an example workflow setup that I recommend you follow: create an R project for your project, and organize all of your data, code, images, & text in this set of folders inside of your project.^[I also recommend you at least save this folder on Dropbox to keep it safe!] You can look at `Example_paper.Rmd` to see my text and code in R markdown to write the paper, and look at `Example_paper.pdf` to see the final product.

The second is a quick and dirty example of what I am looking for in your paper project in this class, using the ongoing example of the effect of class size on test scores. You can also look at `paper.Rmd` to see my text and code in R markdown, and `paper.pdf` to see the final product. Note that this is an example I put quickly together with minimal effort as an example for you all, it does *not* necessarily mean it is an “A” quality paper!

If you are using R markdown to write your final paper, you should consult [class 1.5](/content/1.5-content) again, along with the [1.5 “R practice”](/r/1.5-r) that deals with the workflow repository.

## <i class="fas fa-book-reader fa-lg"></i> Readings

There are no readings for today, but you should look at the materials mentioned above.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-registered"></i> R Practice

Today you will be wrapping up [R practice problems](/r/3.4-r) on multivariate regression. Answers will be posted later on that page.

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 4 Due Tues Nov 9
[Problem Set 4](/assignments/04-problem-set) is due by the end of the day on Tuesday, November 9.