---
title: "4.2 — Difference-in-Difference Models — Class Content"
draft: false
linktitle: "4.2 — Difference-in-Difference Models"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 23
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.2-slides"
---

{{% alert note %}}
*Thursday November 23, 2021*
{{% /alert %}}

{{% alert warning %}}
[Problem Set 5](/assignments/05-problem-set) is due by the end of the day Tuesday, November 23. This will be your final graded problem set!
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today, we look at our last model this semester, one of the most commonly used by professional researchers and econometricians: difference-in-differences, also called “diff-in-diff” or “DND.” The setup of this regression is actually quite simple, consisting (primarily) of a series of dummy variables and an interaction effect:

$$Y_{it}=\beta_0+\beta_1 \text{Before}_{t}+ \beta_2 \text{Treated}_{i}+\beta_3(\text{Before}_i \times \text{Treated}_{t})+u_{it}$$
where 
$$\text{Treated}_i= \begin{cases}1 \text{ if } i \text{ is in treatment group}\\ 0 \text{ if } i \text{ is not in treatment group}\end{cases} \quad \text{After}_t= \begin{cases}1 \text{ if } t \text{ is after treatment period}\\ 0 \text{ if } t \text{ is before treatment period}\end{cases}$$
Thus, $\hat{\beta_3}$ is the causal effect of the treatment we aim to measure. As an interaction effect between two dummies, we can interpret $\hat{\beta_1}$ as measuring the difference across treatment & control group before any treatments happen, $\hat{\beta_2}$ as the difference over time, and $\hat{\beta_3}$ as the difference of the differences:

|    | Control | Treatment | **Group Diff** $(\Delta Y_i)$ |
|----|---------|-----------|---------------------------|
| Before | $\beta_0$ | $\beta_0+\beta_1$ | $\beta_1$ |
| After | $\beta_0+\beta_2$ | $\beta_0+\beta_1+\beta_2+\beta_3$ | $\beta_1+\beta_3$ |
| **Time Diff** $(\Delta Y_t)$ | $\beta_2$ | $\beta_2+\beta_3$ | **Diff-in-diff** $\Delta_i \Delta_t: \beta_3$ |

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 8.5 in Bailey, *Real Econometrics*
- [<i class="fas fa-file-pdf"></i> Dynarski, 1999, “Hope for Whom? Financial Aid for the Middle Class and its Impact on College Attendance”](/readings/Dynarski-1999.pdf)
- [<i class="fas fa-file-pdf"></i> Card and Kreuger, 1994, “Minimum Wages and Unemployment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania”](/readings/Card-Kreuger-1994.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 5 Due Tues Nov 23

[Problem Set 5](/assignments/05-problem-set) is due by the end of the day on Tuesday, November 23. This will be your final graded homework!

### Problem Set 6 Ungraded For Practice

[Problem Set 6](/assignments/06-problem-set) on Unit IV topics may help you study for the final. It will not be collected or graded.