---
date: "2019-05-05T00:00:00+01:00"
draft: false
linktitle: Math Appendices
menu:
  resources:
    parent: Resources
title: List of Math Appendices
toc: true
type: docs
weight: 2
---

| Appendix         | Type | Class |
|------------------|------|------:|
| Budget Constraint for n Goods | Math/Economics | [1.2 class](content/1.2-content/#budget-constraint-for-n-goods) |


# List of Math and R Appendices

The following list contains links to all appendices spread across the Class Notes pages:

- **R**: [Installing R and R Studio](https://metricsf19.classes.ryansafner.com/class/03-class/#installing-r-and-r-studio) (Class 1.3)
- **R**: [R Packages](https://metricsf19.classes.ryansafner.com/class/03-class/#r-packages) (Class 1.3)
- **R**: [Getting Help for R](https://metricsf19.classes.ryansafner.com/class/03-class/#getting-help-for-r) (Class 1.3)
- **R**: [Other Useful Commands to Know](https://metricsf19.classes.ryansafner.com/class/03-class/#other-useful-commands-to-know) (Class 1.3)
- **R**: [Style Guide for Coding](https://metricsf19.classes.ryansafner.com/class/03-class/#style-guide-for-coding) (Class 1.3)
- **Math**: [The Summation Operator](https://metricsf19.classes.ryansafner.com/class/07-class/#the-summation-operator) (Class 2.1)
- **R**: [Creating Mathematical Functions](https://metricsf19.classes.ryansafner.com/class/08-class/#creating-mathematical-functions) (Class 2.2)
- **R**: [Graphing Mathematical Functions](https://metricsf19.classes.ryansafner.com/class/08-class/#graphing-mathematical-functions) (Class 2.2)
- **R**: [Bultin Statistical Functions](https://metricsf19.classes.ryansafner.com/class/08-class/#bultin-statistical-functions) (Class 2.2)
- **R**: [Graphing Statistical Functions](https://metricsf19.classes.ryansafner.com/class/08-class/#graphing-statistical-functions) (Class 2.2)
- **Math**: [Variance](https://metricsf19.classes.ryansafner.com/class/09-class/#variance) (Class 2.3)
- **Math**: [Covariance](https://metricsf19.classes.ryansafner.com/class/09-class/#covariance) (Class 2.3)
- **Math**: [Correlation](https://metricsf19.classes.ryansafner.com/class/09-class/#correlation) (Class 2.3)
- **R**: [Calculating Correlation Example](https://metricsf19.classes.ryansafner.com/class/09-class/#calculating-correlation-example) (Class 2.3)
- **Math**: [Deriving the OLS Estimators](https://metricsf19.classes.ryansafner.com/class/10-class/#deriving-the-ols-estimators) (Class 2.4)
- **Math**: [Algebraic Properties of OLS Estimators](https://metricsf19.classes.ryansafner.com/class/10-class/#algebraic-properties-of-ols-estimators) (Class 2.4)
- **Math**: [Bias in $\hat{\beta_1}$](https://metricsf19.classes.ryansafner.com/class/10-class/#bias-in-hatbeta_1) (Class 2.4)
- **Math**: [Proof of the Unbiasedness of  $\hat{\beta_1}$](https://metricsf19.classes.ryansafner.com/class/10-class/#proof-of-the-unbiasedness-of-hatbeta_1) (Class 2.4)
-->