---
date: "2019-05-05T00:00:00+01:00"
draft: false
linktitle: Data Sources and Suggestions
menu:
  resources:
    parent: Resources
title: Data Resources
toc: true
type: docs
weight: 2
---

##  List of Public Datasets, Data Sources, and R APIs

### Build-in Datasets

- A [near-comprehensive list](https://vincentarelbundock.github.io/Rdatasets/datasets.html) of all existing data sets built-in to R or R packages^[Note: You should use these more for playing around with in R to boost your data wrangling skills. These should not be used for your projects in most circumstances.]

### General Databases of Datasets

- [Google Database Search](https://toolbox.google.com/datasetsearch)
- [Kaggle](https://www.kaggle.com/datasets)
- [Harvard Law School: Find a Database](https://hls.harvard.edu/library/research/find-a-database/#hlsnav-databases-for-legal-and-law-related-research)

### Good R Packages for Getting Data in R Format^[Some of these come from [Nick Huntington-Klein's excellent list](http://www.nickchk.com/econometrics.html).]

Below are packages written by and for R users that link up with the API of key data sets for easy use in R. Each link goes to the documentation and description of each package.

Don't forget to install^[`install.packages("name_of_package")`] first and then load it with `library()`. 

- [`wbstats`](https://cran.r-project.org/web/packages/wbstats/wbstats.pdf) provides access to all the data available on the **World Bank** API, which is basically everything on their website. The World Bank keeps track of *many* country-level indicators over time.
- [`tidycensus`](https://cran.r-project.org/web/packages/tidycensus/tidycensus.pdf) gives you access to data from the **US Census** and the **American Community Survey.** These are the largest high-quality data sets you'll find of cross-sectional data on individual people in the US. You'll need to get a (free) API key from the website (or ask me for mine).
- [`fredr`](https://cran.r-project.org/web/packages/fredr/vignettes/fredr.html) gets data from the **Federal Reserve's Economic Database (FRED)**. You'll need to get a (free) API key from the website (or ask me for mine).
- [`tidyquant`](https://cran.r-project.org/web/packages/tidyquant/index.html) gets data from a number of financial sources (including `fredr`).
- [`icpsrdata`](https://cran.r-project.org/web/packages/icpsrdata/icpsrdata.pdf) downloads data from the **Inter-university Consortium for Political and Social Research** (you'll need an account and a keycode). ICPSR is a database of datasets from published social science papers for the purposes of reproducibility.
- [`NHANES`](https://cran.r-project.org/web/packages/NHANES/NHANES.pdf) uses data from the **US National Health and Nutrition Examination Survey.**
- [`ipumsr`](https://cran.r-project.org/web/packages/ipumsr/vignettes/ipums.html) has **census data** from *all around the world*, in addition to the US census, **American Community Survey**, and **Current Population Survey**. If you're doing international micro work, look at IPUMS. It's also the easiest way to get the **Current Population Survey (CPS)**, which is very popular for labor economics. Unfortunately ipumsr won't get the data from within R; you'll have to make your own data extract on the IPUMS website and download it. But ipumsr will read that file into R and preserve things like names and labels.
- [`education-data-package-r`](https://github.com/UrbanInstitute/education-data-package-r)^[Note you will need to install `devtools` package first, and then install the package directly from Github with the command `devtools::install_github('UrbanInstitute/education-data-package-r')`] is the Urban Institute's data data on educational institutions in the US, including colleges (in IPEDS) and K-12 schools (in CCD). This package also has data on county-level poverty rates from SAIPE.
- [`psidR`](https://cran.r-project.org/web/packages/psidR/psidR.pdf) is the **Panel Study of Income Dynamics**. This study doesn't just follow people over their lifetimes, it follows their children too, generationally! A great source for studying how things follow families through generations.
- [`atus`](https://cran.r-project.org/web/packages/atus/atus.pdf) is th e **American Time Use Survey**, which is a large cross-sectional data set with information on how people spend their time.
- [`Rilostat`](https://ilostat.github.io/Rilostat/index.html) uses data from the **International Labor Organization.** This contains lots of different statistics on labor, like employment, wage gaps, etc., generally aggregated to the national level and changing over time.
- [`democracyData`](https://github.com/xmarquez/democracyData)^[Note you will need to install `devtools` package first, and then install the package directly from Github with the command `devtools::install_github('xmarquez/democracyData')`] is a great "package for accessing and manipulating existing measures of democracy."
- [`politicaldata`](https://cran.rstudio.com/web/packages/politicaldata/index.html) provides useful functions for obtaining commonly-used data in political analysis and political science, including from sources such as the Comparative Agendas Project (which provides data on politics and policy from 20+ countries), the MIT Election and Data Science Lab, and FiveThirtyEight.

Below is a list of good data sources depending on the types of topics you might be interested in writing on:^[Some of these come from various sources, including [https://github.com/awesomedata/awesome-public-datasets#economics](Awesomedata's Awesome Public Datasets for Economics)]

## Key Data Sources

- Coronavirus Data: [John Hopkins CSSE Covid-19 data (definitive)](https://github.com/CSSEGISandData/COVID-19), [Our World in Data](https://github.com/owid/covid-19-data/tree/master/public/data), [New York Times Covid data](https://github.com/nytimes/covid-19-data), [`covdata` r package](https://github.com/kjhealy/covdata), [Tidy Covid data](https://github.com/joachim-gassen/tidycovid19)

- [American Economic Association Data](https://www.aeaweb.org/resources/data)
- [EconData from UMD](http://inforumweb.umd.edu/econdata/econdata.html)
- [Historical Macroeconomic Statistics](http://www.historicalstatistics.org/)
- [UMD's Interindustry Forecasting](http://inforumweb.umd.edu/econdata/econdatacontents.html)
- [DB-nomics](https://db.nomics.world/)
- [Internet UPC Database](https://www.upcdatabase.com/)
- [International Trade Data](https://www.macalester.edu/research/economics/PAGE/HAVEMAN/Trade.Resources/TradeData.html)
- [OurWorldinData.org](https://ourworldindata.org/) ([download datasets](https://github.com/owid/owid-datasets))
- [SciencesPo International Trade Gravity Dataset](http://econ.sciences-po.fr/thierry-mayer/data)
- [Center for International Data](https://cid.econ.ucdavis.edu/)
- [Atlas of Economic Complexity](http://atlas.cid.harvard.edu/)
- [U.N. World Development Reports](http://hdr.undp.org/en)
- [Observatory of Economic Complexity](https://oec.world/en/)
- [Reddit /r/datasets](https://www.reddit.com/r/datasets/)
- [Google Cloud Public Datasets](https://cloud.google.com/public-datasets/)

**By Topic**

- [Quality of Government Data](https://qog.pol.gu.se/data/dataextras/datasources) has an extremely wide range of data sources pertaining to measures of institutions. The data itself can be found [here](https://qog.pol.gu.se/data/datadownloads/qogstandarddata). 
- National and State Accounts Data: [Bureau of Economic Analysis](http://www.bea.doc.gov/)
- Labor Market and Price Data: [Bureau of Labor Statistics](http://www.bls.gov/)
- Macroeconomic Data: [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/), [World Development Indicators (World Bank)](https://datacatalog.worldbank.org/dataset/world-development-indicators), [Penn World Table](https://www.rug.nl/ggdc/productivity/pwt/)
- International Data: [NationMaster.com](http://www.nationmaster.com/), [Doing Business](http://rru.worldbank.org/DoingBusiness/), [CIESIN](ttp://www.ciesin.org/data.html)
- Census Data: [U.S. Census Bureau](http://www.census.gov/)
- Sports Data: [Spotrac](http://spotrac.com), [Rodney Fort's Sports Data](https://sites.google.com/site/rodswebpages/codes)
- Data Clearing House: [Stat USA](http://www.stat-usa.gov/), [Fedstats](http://www.fedstats.gov/), [Statistical Abstract of the United States](http://www.census.gov/prod/www/statistical-abstract-us.html), [Resources for Economists](http://rfe.org) 
- Political and Social Data: [ICPSR](http://www.icpsr.umich.edu/), [Federal Election Commission](http://fec.gov), [Poole and Rosenthal Roll Call Data (Voting ideology)](http://voteview.uh.edu/default_nomdata.htm), [Archigos Data on Political Leaders](https://www.rochester.edu/college/faculty/hgoemans/data.htm), [Library of Congress: Thomas (Legislation)](http://thomas.loc.gov/), [Iowa Electronic Markets (Prediction Markets)](http://www.biz.uiowa.edu/iem/)
- War and Violence Data: [Correlates of War](http://www.correlatesofwar.org/data-sets)
- State Level Data: [Correlates of State Policy](http://ippsr.msu.edu/public-policy/correlates-state-policy)
- Health Data: [Centers for Disease Control](http://www.cdc.gov/scientific.htm), [CDC Wonder System](http://wonder.cdc.gov/DataSets.shtml)
- Crime Data: [Bureau of Justice Statistics](http://www.ojp.usdoj.gov/bjs/)
- Education Data: [National Center for Education Statistics](http://www.nces.ed.gov/)
- Environmental Data: [EPA](http://www.epa.gov/ceisweb1/ceishome/)
- Religion Data: [American Religion Data Archiva (ARDA)](http://www.arda.tm/)
- Financial Data: [Financial Data Finder](http://www.cob.ohio-state.edu/cgi-bin/DB_Search/db_search.cgi?setup_file=finance.setup.cgi){Financial Data Finder}
- Philanthropy Data: [The Urban Institute](http://nccs.urban.org/)
